services:
  rulebook_app:
    container_name: "rulebookmaster_app"
    image: "rulebookmaster_image"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1
    ports:
      - "5000:5000"
